### ISSUE TITLE
Buchstaben Schablone verfügbar ?

### ISSUE THREAD

**Issue by AWSW-de** [highno/wordclock_mini#1]
Hallo,

zunächst mal ein großes Lob für diese coole Idee.

Von diesen MAX7219 Matrix und D1 mini habe ich auch noch ein paar hier rumfliegen. Daher wollte ich das Teil mal angehen. Leider finde ich im .STL für den Druck noch hier die Buchstaben Schablone.

Ich dachte, dass sie im .STL integriert ist, aber das scheint nicht so zu sein oder?
Würde mich freuen, die Vorlage erhalten zu können. 

Danke vorab.

Viele Grüße

**Comment by highno** [comment]
Hallo und sorry für die lange Verzögerung. Mir ist die Notification zu diesem Projekt offenbar durchgeschlüpft...
Danke - ich habe (eher zufällig) gestern mal wieder meine alten Projekte durchgeflöht und bin bei diesem hängen geblieben, weil ich nach einem Umzug was Nettes für den Desktop suchte. 
Dabei ist mir aufgefallen, dass der Code hie ja noch für die Arduino-Umgebung und nicht wie von mir bevorzugt für PlatformIO ist. Auch ist die Homie Lib veraltet, ich habe meinen Code zu Hause schon umgestellt und lade ihn nachher mal hoch. Als PlatformIO Projekt mit Homie 3.0.1 Unterstützung (und ArduinoJson 6.x anstelle 5.x wie hier noch...)
Zuerst aber lade ich schon mal in das Docs-Verzeichnis die Buchstaben-Map hoch, wobei sie auf dem Foto ja auch bereits zu sehen ist. Ich werde in meiner aktuellen Fassung noch experimentieren mit einer roten Folie davor, dann werden die "leeren" Buchstaben noch besser versteckt.

Falls Du diese Weihnachten noch nichts vor hast - diese Update können wir gerne gemeinsam remote bauen :-)

**Comment by highno** [comment]
Die Anleitung zum Aufbau samt der Matrix der Buchstaben ist nun als [PDF-Dokument](https://github.com/highno/wordclock_mini/blob/master/docs/Projekt%20LED-Matrix%20Wordclock%208x8.pdf) mit integriert.

**Comment by highno** [comment]
So, nun ist auch die neue Struktur umgesetzt. Der ganze Spaß nun also als PlatformIO mit neuen Libs und deren Abhängigkeiten.
Leider benötigt Homie noch SPIFFS und nicht LittleFS, daher gibt es viele Warnungen. Aber es sollte trotzdem klappen.
Viel Spaß bei der Umsetzung - falls noch aktuell.

**Comment by AWSW-de** [comment]
Hallo,
besten Dank dafür. Mit PlatformIO habe ich mich bisher noch nicht beschäftigt. Würde das wenn noch mit Arduino umsetzen wollen. Der D1 Mini ist dafür imho prädestiniert. Die Teile für dieses Projekt hatte ich mir zwischenzeitlich schon beschafft. Was mir fehlte war die Buchstabenschablone... Ich schau mir die neuen Dateien gleich mal an. 

Aktuell überlege ich noch etwas größer: https://www.thingiverse.com/thing:4693081
Dürfte auch gut aussehen, denke ich.

Vielen Dank für Deine Mühe und ich schaue mir nachher die Dateien mal genauer an.

Viele Grüße 😊
